name: Deploy Page

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    name: Build and Upload to github page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 📦 Install node modules
        run: |
          yarn install
          yarn build
      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_DEPLOY_KEY }}
          external_repository: ${{ github.repository }}-page
          publish_branch: main
          publish_dir: ./build
          cname: front.devfive.kr
