name: PR Confirm

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    name: Build Confirm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 📦 Install Dependencies
        run: yarn install
      - name: 🚀 Build project
        run: yarn build
